language: python
python:
  - "3.12"
install:
  - pip install -r requirements/test.txt
  - pip install -r requirements/coverage.txt
  - pip install -e .
script: 
  - python -m pytest --cov=iolpy tests/
after_success:
  - codecov