name: CI

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{github.workflow}}-${{ github.ref == 'refs/heads/main' && github.run_humber || github.ref }}
  cancel-in-progress: true # Cancel jobs rom previous push

jobs:
  build_and_test:
    name: build and test ${{ matrix.variant.os }}, py${{matrix.python-version }}
    runs-on: ${{ matrix.variant.os }}
    defaults:
      run:
        shell: bash -l {0} # required for conda env
    strategy:
      fail-fast: false
      matrix:
        variant:
          - {os: ubuntu-22.04}
        python-version: ["3.10"]
    
    permissions:
      contents: read

    steps:
      - uses: action/checkout@v4
        with:
          fetch-depth: true
          repository: LeanoA/iolpy
      
      - name: Setup conda environment
        uses: mamba-org/setup-micromamba@v1
        with:
          micromamba-version: '1.5.6-0' # any version from https://github.com/mamba-org/micromamba-releases
          environment-file: developer.yml
          cache-environment: true
          create-args: python=${{ matrix.variant.python-version }}
    
      - run: tox -e import-minimal
      - run: tox -e test
